//
// Generated file, do not edit! Created by nedtool 5.3 from FreeMsg.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __FREEMSG_M_H
#define __FREEMSG_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0503
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>FreeMsg.msg:2</tt> by nedtool.
 * <pre>
 * packet FreeMsg
 * {
 *     int port;
 *     int vcid;
 * }
 * </pre>
 */
class FreeMsg : public ::omnetpp::cPacket
{
  protected:
    int port;
    int vcid;

  private:
    void copy(const FreeMsg& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const FreeMsg&);

  public:
    FreeMsg(const char *name=nullptr, short kind=0);
    FreeMsg(const FreeMsg& other);
    virtual ~FreeMsg();
    FreeMsg& operator=(const FreeMsg& other);
    virtual FreeMsg *dup() const override {return new FreeMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getPort() const;
    virtual void setPort(int port);
    virtual int getVcid() const;
    virtual void setVcid(int vcid);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const FreeMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, FreeMsg& obj) {obj.parsimUnpack(b);}


#endif // ifndef __FREEMSG_M_H

