//
// Generated file, do not edit! Created by nedtool 5.1 from BufferFreeMsg.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __BUFFERFREEMSG_M_H
#define __BUFFERFREEMSG_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0501
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>BufferFreeMsg.msg:8</tt> by nedtool.
 * <pre>
 * packet BufferFreeMsg
 * {
 *     int port;
 *     int vcid;
 * }
 * </pre>
 */
class BufferFreeMsg : public ::omnetpp::cPacket
{
  protected:
    int port;
    int vcid;

  private:
    void copy(const BufferFreeMsg& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const BufferFreeMsg&);

  public:
    BufferFreeMsg(const char *name=nullptr, short kind=0);
    BufferFreeMsg(const BufferFreeMsg& other);
    virtual ~BufferFreeMsg();
    BufferFreeMsg& operator=(const BufferFreeMsg& other);
    virtual BufferFreeMsg *dup() const override {return new BufferFreeMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getPort() const;
    virtual void setPort(int port);
    virtual int getVcid() const;
    virtual void setVcid(int vcid);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const BufferFreeMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, BufferFreeMsg& obj) {obj.parsimUnpack(b);}


#endif // ifndef __BUFFERFREEMSG_M_H

