//
// Generated file, do not edit! Created by nedtool 5.2 from credit.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __CREDIT_M_H
#define __CREDIT_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0502
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>credit.msg:2</tt> by nedtool.
 * <pre>
 * packet credit
 * {
 *     int os;
 *     int port;
 *     int vc;
 * }
 * </pre>
 */
class credit : public ::omnetpp::cPacket
{
  protected:
    int os;
    int port;
    int vc;

  private:
    void copy(const credit& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const credit&);

  public:
    credit(const char *name=nullptr, short kind=0);
    credit(const credit& other);
    virtual ~credit();
    credit& operator=(const credit& other);
    virtual credit *dup() const override {return new credit(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getOs() const;
    virtual void setOs(int os);
    virtual int getPort() const;
    virtual void setPort(int port);
    virtual int getVc() const;
    virtual void setVc(int vc);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const credit& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, credit& obj) {obj.parsimUnpack(b);}


#endif // ifndef __CREDIT_M_H

