//
// Generated file, do not edit! Created by nedtool 5.2 from exchange.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __EXCHANGE_M_H
#define __EXCHANGE_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0502
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>exchange.msg:1</tt> by nedtool.
 * <pre>
 * packet exchange
 * {
 *     int type;  // 0 for remote, 1 for local
 *     int os;
 *     int port;
 *     int vc;
 *     int credit;
 * }
 * </pre>
 */
class exchange : public ::omnetpp::cPacket
{
  protected:
    int type;
    int os;
    int port;
    int vc;
    int credit;

  private:
    void copy(const exchange& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const exchange&);

  public:
    exchange(const char *name=nullptr, short kind=0);
    exchange(const exchange& other);
    virtual ~exchange();
    exchange& operator=(const exchange& other);
    virtual exchange *dup() const override {return new exchange(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getType() const;
    virtual void setType(int type);
    virtual int getOs() const;
    virtual void setOs(int os);
    virtual int getPort() const;
    virtual void setPort(int port);
    virtual int getVc() const;
    virtual void setVc(int vc);
    virtual int getCredit() const;
    virtual void setCredit(int credit);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const exchange& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, exchange& obj) {obj.parsimUnpack(b);}


#endif // ifndef __EXCHANGE_M_H

